# -*- coding: utf-8 -*-
"""Mini_P

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzjTloJF8GRXkuEsiyyj9odZBuc5iYfD

## 1. Data Loading and Initial Exploration
"""

import pandas as pd

data = pd.read_csv("/content/StudentPerformanceFactors.csv")

print("Dataset loaded successfully into 'data' DataFrame.")

print("Dataset Shape:", data.shape)
print("\nDataset Size:", data.size)

display("First 5 Rows of Dataset:", data.head())

"""## 2. Data Preprocessing"""

data.info()

display("Missing values before handling:\n", data.isnull().sum())

"""### 2. Checking for Duplicates"""

duplicate_rows = data.duplicated().sum()

print(f"Number of duplicate rows found: {duplicate_rows}")

"""### Converting Data Types"""

print("Data types before conversion:\n")
print(data.dtypes)

for col in data.select_dtypes(include='object').columns:
    data[col] = data[col].astype('category')

print("\nData types after conversion:\n")
print(data.dtypes)

"""## 3. Outlier Detection and Handling"""

import numpy as np

numerical_cols = data.select_dtypes(include=np.number).columns

print("Number of outliers :")
for col in numerical_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)]
    print(f"  {col}: {len(outliers)}")

import numpy as np

numerical_cols = data.select_dtypes(include=np.number).columns

print("Number of outliers before :")
for col in numerical_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)]
    print(f"  {col}: {len(outliers)}")

    # Apply winsorization (capping)
    data[col] = np.clip(data[col], lower_bound, upper_bound)

print("\nNumber of outliers after :")
for col in numerical_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)]
    print(f"  {col}: {len(outliers)}")

"""## 4. Data Splitting for Model Training"""

X = data[['Hours_Studied', 'Attendance']]
y = data['Exam_Score']

print("Shape of X (features):")
print(X.shape)
print("\nShape of y (target):")
print(y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""## 4.1 Feature Engineering: Encoding Categorical Variables"""

# Select categorical columns to encode (excluding 'Exam_Score' and numerical columns already in X)
categorical_cols = data.select_dtypes(include='category').columns.tolist()

# Exclude target variable if it's accidentally in categorical_cols
if 'Exam_Score' in categorical_cols:
    categorical_cols.remove('Exam_Score')

print(f"Categorical columns to encode: {categorical_cols}")

# Apply one-hot encoding
data_encoded = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

# Update X to include all features from the encoded data except the target variable 'Exam_Score'
X_all_features = data_encoded.drop('Exam_Score', axis=1)

# Display the shape and a sample of the new feature set
print(f"\nShape of X_all_features after encoding: {X_all_features.shape}")
print("\nFirst 5 rows of X_all_features:")
display(X_all_features.head())

"""## 5. Model Training and Prediction (Initial Models)

### 5.1 Training Initial Models
"""

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Lasso

#Linear Regression
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

#Decision Tree
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)

#Random Forest Regressor
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

#K-Nearest Neighbors Regressor
knn_model = KNeighborsRegressor()
knn_model.fit(X_train, y_train)

#Lasso Regression
lasso_model = Lasso(random_state=42)
lasso_model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")
print("Decision Tree Regressor model trained successfully.")
print("Random Forest Regressor model trained successfully.")
print("K-Nearest Neighbors Regressor model trained successfully.")
print("Lasso Regression model trained successfully.")

"""### 5.2 Generating Initial Predictions"""

lr_predictions = lr_model.predict(X_test)
dt_predictions = dt_model.predict(X_test)
rf_predictions = rf_model.predict(X_test)
knn_predictions = knn_model.predict(X_test)
lasso_predictions = lasso_model.predict(X_test)

print("Predictions for Linear Regression model generated successfully.")
print("Predictions for Decision Tree Regressor model generated successfully.")
print("Predictions for Random Forest Regressor model generated successfully.")
print("Predictions for K-Nearest Neighbors Regressor model generated successfully.")
print("Predictions for Lasso Regression model generated successfully.")

"""### 5.3 Clipping Initial Predictions"""

lr_predictions = np.clip(lr_predictions, 0, 100)
dt_predictions = np.clip(dt_predictions, 0, 100)
rf_predictions = np.clip(rf_predictions, 0, 100)
knn_predictions = np.clip(knn_predictions, 0, 100)
lasso_predictions = np.clip(lasso_predictions, 0, 100)

print("Predicted marks clipped to a realistic range of 0 to 100 for both models.")

"""## 6. Model Evaluation and Comparison"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Calculate MAE and MSE for Linear Regression
lr_mae = mean_absolute_error(y_test, lr_predictions)
lr_mse = mean_squared_error(y_test, lr_predictions)

# Calculate MAE and MSE for Decision Tree
dt_mae = mean_absolute_error(y_test, dt_predictions)
dt_mse = mean_squared_error(y_test, dt_predictions)

# Calculate MAE and MSE for RandomForest
rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_mse = mean_squared_error(y_test, rf_predictions)

# Calculate MAE and MSE for KNN
knn_mae = mean_absolute_error(y_test, knn_predictions)
knn_mse = mean_squared_error(y_test, knn_predictions)

# Calculate MAE and MSE for Lasso
lasso_mae = mean_absolute_error(y_test, lasso_predictions)
lasso_mse = mean_squared_error(y_test, lasso_predictions)

# Print the results
print(f"Linear Regression MAE: {lr_mae:.2f}")
print(f"Linear Regression MSE: {lr_mse:.2f}")
print(f"Decision Tree MAE: {dt_mae:.2f}")
print(f"Decision Tree MSE: {dt_mse:.2f}")
print(f"Random Forest MAE: {rf_mae:.2f}")
print(f"Random Forest MSE: {rf_mse:.2f}")
print(f"KNN MAE: {knn_mae:.2f}")
print(f"KNN MSE: {knn_mse:.2f}")
print(f"Lasso Regression MAE: {lasso_mae:.2f}")
print(f"Lasso Regression MSE: {lasso_mse:.2f}")

import matplotlib.pyplot as plt

# 1. Bar chart for MSE comparison
mse_values = [lr_mse, dt_mse, rf_mse, knn_mse, lasso_mse]
model_names = ['Linear Regression', 'Decision Tree', 'Random Forest', 'KNN', 'Lasso']

plt.figure(figsize=(12, 6))
plt.bar(model_names, mse_values, color=['skyblue', 'lightcoral', 'lightgreen', 'gold', 'violet'])
plt.ylabel('MSE Value')
plt.title('Comparison of MSE for Different Regression Models')
plt.grid(axis='y', linestyle='--', alpha=0.7) #70% visible
plt.show()

# 2. Bar chart for MAE comparison
mae_values = [lr_mae, dt_mae, rf_mae, knn_mae, lasso_mae]
model_names = ['Linear Regression', 'Decision Tree', 'Random Forest', 'KNN', 'Lasso']

plt.figure(figsize=(12, 6))
plt.bar(model_names, mae_values, color=['skyblue', 'lightcoral', 'lightgreen', 'gold', 'violet'])
plt.ylabel('MAE Value')
plt.title('Comparison of MAE for Different Regression Models')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### 7. Visualizing Actual vs. Predicted Scores"""

import matplotlib.pyplot as plt

# Scatter plot for Linear Regression: Actual vs. Predicted
plt.figure(figsize=(10, 6))
plt.scatter(y_test, lr_predictions, alpha=0.6, label='Predicted Scores')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Perfect Prediction')
plt.xlabel('Actual Exam Score')
plt.ylabel('Predicted Exam Score')
plt.title('Linear Regression: Actual vs. Predicted Exam Scores')
plt.legend()
plt.grid(True)
plt.show()

# Scatter plot for Decision Tree: Actual vs. Predicted
plt.figure(figsize=(10, 6))
plt.scatter(y_test, dt_predictions, alpha=0.6, label='Predicted Scores')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Perfect Prediction')
plt.xlabel('Actual Exam Score')
plt.ylabel('Predicted Exam Score')
plt.title('Decision Tree: Actual vs. Predicted Exam Scores')
plt.legend()
plt.grid(True)
plt.show()

# Scatter plot for Random Forest: Actual vs. Predicted
plt.figure(figsize=(10, 6))
plt.scatter(y_test, rf_predictions, alpha=0.6, label='Predicted Scores')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Perfect Prediction')
plt.xlabel('Actual Exam Score')
plt.ylabel('Predicted Exam Score')
plt.title('Random Forest: Actual vs. Predicted Exam Scores')
plt.legend()
plt.grid(True)
plt.show()

# Scatter plot for KNN: Actual vs. Predicted
plt.figure(figsize=(10, 6))
plt.scatter(y_test, knn_predictions, alpha=0.6, label='Predicted Scores')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Perfect Prediction')
plt.xlabel('Actual Exam Score')
plt.ylabel('Predicted Exam Score')
plt.title('KNN: Actual vs. Predicted Exam Scores')
plt.legend()
plt.grid(True)
plt.show()

# Scatter plot for Lasso Regression: Actual vs. Predicted
plt.figure(figsize=(10, 6))
plt.scatter(y_test, lasso_predictions, alpha=0.6, label='Predicted Scores')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Perfect Prediction')
plt.xlabel('Actual Exam Score')
plt.ylabel('Predicted Exam Score')
plt.title('Lasso Regression: Actual vs. Predicted Exam Scores')
plt.legend()
plt.grid(True)
plt.show()

"""## 8. Predicting with User Input"""

import numpy as np
import pandas as pd

# 1. Prompt for 'Hours Studied'
while True:
    try:
        hours_studied = float(input("Enter the number of hours studied (not more than 12): "))
        if hours_studied > 12:
            print("Invalid input. Hours studied cannot be more than 12.")
        else:
            break
    except ValueError:
        print("Invalid input. Please enter a numerical value for hours studied.")

# 2. Prompt for 'Attendance'
while True:
    try:
        attendance = float(input("Enter the attendance percentage (e.g., 85 for 85%): "))
        break
    except ValueError:
        print("Invalid input. Please enter a numerical value for attendance.")

# 3. Create a single Pandas DataFrame with user input for all models
user_input_for_all_models = pd.DataFrame({
    'Hours_Studied': [hours_studied],
    'Attendance': [attendance]
})

# 4. Predict the 'Exam_Score' using each model
predicted_score_lr = lr_model.predict(user_input_for_all_models)
predicted_score_dt = dt_model.predict(user_input_for_all_models)
predicted_score_rf = rf_model.predict(user_input_for_all_models)
predicted_score_knn = knn_model.predict(user_input_for_all_models)
predicted_score_lasso = lasso_model.predict(user_input_for_all_models)

# 5. Apply realistic constraints (clip to 0-100)
predicted_score_lr_clipped = np.clip(predicted_score_lr, 0, 100)
predicted_score_dt_clipped = np.clip(predicted_score_dt, 0, 100)
predicted_score_rf_clipped = np.clip(predicted_score_rf, 0, 100)
predicted_score_knn_clipped = np.clip(predicted_score_knn, 0, 100)
predicted_score_lasso_clipped = np.clip(predicted_score_lasso, 0, 100)

# 6. Print the predicted exam scores for all models
print(f"\n--- Predicted Exam Scores based on User Input ---")
print(f"Predicted Exam Score (Linear Regression): {predicted_score_lr_clipped[0]:.2f}")
print(f"Predicted Exam Score (Decision Tree Regressor): {predicted_score_dt_clipped[0]:.2f}")
print(f"Predicted Exam Score (Random Forest Regressor): {predicted_score_rf_clipped[0]:.2f}")
print(f"Predicted Exam Score (K-Nearest Neighbors Regressor): {predicted_score_knn_clipped[0]:.2f}")
print(f"Predicted Exam Score (Lasso Regression): {predicted_score_lasso_clipped[0]:.2f}")

import matplotlib.pyplot as plt
import plotly.express as px

# Create a DataFrame for comparison of user input predictions
prediction_summary = pd.DataFrame({
    'Model': ['Linear Regression', 'Decision Tree', 'Random Forest', 'KNN', 'Lasso'],
    'Predicted Score': [
        predicted_score_lr_clipped[0],
        predicted_score_dt_clipped[0],
        predicted_score_rf_clipped[0],
        predicted_score_knn_clipped[0],
        predicted_score_lasso_clipped[0]
    ]
})

# Create the bar chart
fig = px.bar(
    prediction_summary,
    x='Model',
    y='Predicted Score',
    color='Model',
    title='Comparison of Predicted Exam Scores for User Input',
    labels={'Predicted Score': 'Predicted Exam Score'},
    text='Predicted Score'
)

fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig.update_layout(uniformtext_minsize=8, uniformtext_mode='hide')

fig.show()

"""## 9. Deploying Models with Streamlit"""

# Install necessary packages
!pip install streamlit pyngrok -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(layout="wide")
# 
# st.title('Student Performance Dashboard')
# 
# # Load dataset
# @st.cache_data
# def load_data():
#     try:
#         df = pd.read_csv('/content/StudentPerformanceFactors.csv')
# 
#         # Encode Gender
#         df = pd.get_dummies(df, columns=['Gender'], drop_first=True)
# 
#         # Apply maximum limit for 'Hours_Studied'
#         df['Hours_Studied'] = df['Hours_Studied'].clip(upper=12)
# 
#         # Create Performance Category based on Exam Score
#         bins = [0, 50, 75, 100]
#         labels = ['Low', 'Medium', 'High']
#         df['Performance_Category'] = pd.cut(df['Exam_Score'], bins=bins, labels=labels)
# 
#         return df
# 
#     except FileNotFoundError:
#         st.error("Dataset not found at '/content/StudentPerformanceFactors.csv'. Please ensure the file is present.")
#         return pd.DataFrame()
# 
# dataset = load_data()
# 
# if not dataset.empty:
# 
#     # Preview
#     st.subheader('Raw Data')
#     st.dataframe(dataset.head())
# 
#     # Performance distribution
#     st.subheader('Student Performance Distribution')
#     fig_perf = px.bar(
#         dataset['Performance_Category'].value_counts().reset_index(name='Count'),
#         x='Performance_Category', y='Count',
#         color='Performance_Category',
#         title='Students by Performance Category'
#     )
#     st.plotly_chart(fig_perf, use_container_width=True)
# 
#     # Exam score vs study hours
#     st.subheader('Hours Studied vs Exam Score')
#     fig_scatter = px.scatter(
#         dataset,
#         x='Hours_Studied',
#         y='Exam_Score',
#         color='Performance_Category',
#         size='Attendance',
#         hover_data=['Motivation_Level', 'Sleep_Hours'],
#         title='Study Hours Impact on Exam Score'
#     )
#     st.plotly_chart(fig_scatter, use_container_width=True)
# 
#     # Attendance vs score
#     st.subheader('Attendance vs Exam Score')
#     fig_att = px.scatter(
#         dataset,
#         x='Attendance',
#         y='Exam_Score',
#         color='Performance_Category',
#         title='Attendance Impact'
#     )
#     st.plotly_chart(fig_att, use_container_width=True)
# 
#     # Correlation Heatmap
#     st.subheader('Correlation Heatmap')
#     numeric_df = dataset.select_dtypes(include=['int64', 'float64'])
#     fig_corr = px.imshow(numeric_df.corr(), text_auto=True, title="Feature Correlation")
#     st.plotly_chart(fig_corr, use_container_width=True)
# 
#     # Filters
#     st.subheader('Filter Students')
# 
#     # Performance Category Filter
#     selected_category = st.selectbox(
#         'Select Performance Category:',
#         options=['All'] + list(dataset['Performance_Category'].dropna().unique())
#     )
# 
#     # Attendance Filter
#     min_attendance, max_attendance = st.slider(
#         'Select Attendance Range (%):',
#         min_value=int(dataset['Attendance'].min()),
#         max_value=int(dataset['Attendance'].max()),
#         value=(int(dataset['Attendance'].min()), int(dataset['Attendance'].max()))
#     )
# 
#     # Apply filters
#     filtered_df = dataset.copy()
# 
#     if selected_category != 'All':
#         filtered_df = filtered_df[filtered_df['Performance_Category'] == selected_category]
# 
#     filtered_df = filtered_df[
#         (filtered_df['Attendance'] >= min_attendance) &
#         (filtered_df['Attendance'] <= max_attendance)
#     ]
# 
#     st.dataframe(filtered_df)

import subprocess
import os
from pyngrok import ngrok
from google.colab import userdata
import time

# Terminate ngrok processes if any are running
ngrok.kill()

# Get ngrok authentication token from Colab secrets
NGROK_AUTH_TOKEN = userdata.get('NGROK_AUTH_TOKEN')

if not NGROK_AUTH_TOKEN:
    raise ValueError("NGROK_AUTH_TOKEN not found in Colab secrets. Please set it.")

ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Start Streamlit in a separate process
# The 'preexec_fn=os.setsid' is used to detach the child process from the parent
streamlit_process = subprocess.Popen(['streamlit', 'run', 'dashboard.py'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, preexec_fn=os.setsid)

# Allow some time for Streamlit to start
time.sleep(5)

# Open a ngrok tunnel to the Streamlit app port (8501)
public_url = ngrok.connect(8501)

print(f"Streamlit App is live at: {public_url}")

# You can access the Streamlit app using the public_url provided above.
# The tunnel will remain active as long as this cell is running.
# To stop it, interrupt the kernel or manually stop the ngrok process.

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    print("\nStopping Streamlit and ngrok processes...")
    if streamlit_process.poll() is None:
        os.killpg(os.getpgid(streamlit_process.pid), 15) # SIGTERM
    ngrok.kill()
    print("Processes stopped.")